config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  resources :lists do
    resources :tasks, module: "lists" do
      member do
        post 'status'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
  validates_associated :tasks

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
  after_update_commit { broadcast_replace_to 'lists' }
  after_destroy_commit { broadcast_remove_to 'lists' }
end

app/models/task.rb
class Task < ApplicationRecord
  enum status: [:incomplete, :complete]

  belongs_to :list

  validates :description, presence: true
  validates :list, presence: true
  validates :status, inclusion: { in: statuses.keys, message: :invalid }

  # before_save :initialize_position, if: Proc.new { |task| task.list.tasks.empty? }
  # before_save :check_for_status_change

  after_destroy_commit do
    broadcast_update_to(list,
                        :tasks,
                        target: 'incomplete-tasks',
                        partial: 'lists/incomplete_tasks',
                        locals: { list: list,
                                  tasks: list.tasks.incomplete })
  end

  # def initialize_position
  #   self.position = 0
  # end

  # def transition_status
  #   p "in transition status"
  # end

  private

  # def check_for_status_change
  #   return if new_record?
  #   transition_status if status_changed?
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def render_flash
    render turbo_stream: turbo_stream.update("flash", partial: "shared/flash")
  end
end

app/controllers/lists/tasks_controller.rb
class Lists::TasksController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :set_list, except: [:index, :show]
  before_action :set_task, except: [:new, :create]

  def new
    @task = Task.new
  end

  def create
    respond_to do |format|
      if @list.update(list_params)
        flash[:notice] = 'Saved'
        format.turbo_stream { render_flash }
        format.html { redirect_to list_path(@list) }
      else
        format.html { render :new, status: :unprocessable_entity,
                                   notice: 'Sorry, but your task was not created, please try again.'
        }
      end
    end
  end

  def edit
    @list = List.find(params[:list_id])
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(dom_id(@task), partial: 'lists/tasks/incomplete_task_item')
        end
        format.html { redirect_to list_path(@list) }
      else
        format.html { redirect_to list_path(@list), notice: 'Your task was not updated, please try again.' }
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to list_path(@list)
  end

  def status
    status = params[:status]
    respond_to do |format|
      if @task.update!(status: status)
        format.turbo_stream
      else
        p 'something went wrong'
      end
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def list_params
    params.require(:list).permit(tasks_attributes: [:_destroy,
                                                    :description,
                                                    :id,
                                                    :list_id])
  end

  def task_params
    params.require(:task).permit(:list_id, :description, :position, :status)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :set_list, except: [:index, :new, :create]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    respond_to do |format|
      if @list.save
        flash[:notice] = "List was created"
        format.turbo_stream { render_flash }
        format.html { redirect_to list_path(@list)}
      else
        format.html { render :new, status: :unprocessable_entity, notice: "Sorry, but your list was not created, please try again." }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(dom_id(@list),
                                     partial: 'lists/list') }
        format.html { redirect_to lists_path }
      else
        format.html { render :new, status: :unprocessable_entity, notice: "Sorry, but your list was not updated, please try again." }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      flash.now[:notice] = "List was deleted"
      format.turbo_stream { render_flash }
      format.html { redirect_to lists_path }
    end
  end

  def show; end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name,
                                 tasks_attributes: [:_destroy,
                                                    :description,
                                                    :id,
                                                    :list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="min-h-screen flex flex-col bg-tan">
    <main class="flex-1">
      <div class="max-w-lg mx-auto">
        <turbo-frame id="flash">
          <%= render 'shared/flash' %>
        </turbo-frame>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/_complete_tasks.html.erb
<% list = @list if @list.present? %>
<% if tasks.size > 0 %>
  <p class="mb-3 font-semibold mt-6">Completed tasks</p>
<% end %>
<ul class="mb-6">
  <% tasks.complete.each do |task| %>
    <li class="mb-2" data-controller="task">
      <div class="flex gap-4 items-start">
        <div class="flex-none">
          <div class="flex-none">
            <input type="checkbox"
                    data-action="task#updateStatus"
                    data-task-target="complete"
                    data-task-list-value="<%= list.id %>"
                    data-task-task-value="<%= task.id %>"
                    <% if task.complete? %> checked <% end %> >
          </div>

        </div>
        <div class="flex-1"><%= task.description %></div>
      </div>
    </li>
  <% end %>
</ul>

app/views/lists/_form.html.erb
<%= form_with(model: list, url: lists_path, method: :post, data: { turbo: false }) do |form| %>
  <div class="mb-4" id="name">
    <%= form.label :name, "Give your to-do list a name" %>
    <%= form.text_field :name, class:'border p-2 w-full', placeholder: "i.e. 'Super Bowl festivities' " %>
  </div>
  <div class="flex items-center">
    <%= form.button class: "btn-primary" do %>
      <span class="show-when-enabled">
        <%= list.new_record? ? "Create to-do list" : "Update to-do list" %>
      </span>
      <span class="show-when-disabled">Creating...</span>
    <% end %>
    <a href="/" class="text-sm ml-4">Nevermind, take me back</a>
  </div>
<% end %>

app/views/lists/_incomplete_tasks.html.erb
<% list = @list if @list.present? %>
<% if tasks.size > 0 %>
  <p class="mb-3 font-semibold mt-6">Incompleted tasks</p>
<% end %>
<ul class="mb-6">
  <% tasks.each do |task| %>
    <li class="mb-2" data-controller="task">
      <%= turbo_frame_tag dom_id(task) do %>
        <div class="flex gap-4 items-start">
          <div class="flex-none" >
            <input type="checkbox"
                    data-action="task#updateStatus"
                    data-task-target="complete"
                    data-task-list-value="<%= list.id %>"
                    data-task-task-value="<%= task.id %>"
                    <% if task.complete? %> checked <% end %> >
          </div>

          <div class="flex-1"><%= task.description %></div>
          <div class="flex space-x-2">
            <span class="text-sm">
              <%= link_to "Edit", edit_list_task_path(list_id: list.id, id: task.id) %>
            </span>
            <span class="text-sm">
              <%= button_to "Delete",
                            list_task_path(list, task),
                            method: :delete,
                            class: 'text-red-500 hover:text-red-600 text-sm underline hover:no-underline',
                            form: { data: { turbo_confirm: "Are you sure?" }  }%>
            </span>
          </div>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/lists/_list.html.erb
<% list = @list if @list.present? %>
<ul class="mb-6">
  <li class="mb-2">
    <%= turbo_frame_tag dom_id(list) do %>
      <div class="flex justify-between items-center">
        <div>
          <%= link_to list.name, list_path(list), data: { turbo_frame: "_top"} %> <%= content_tag(:span, "#{list.tasks.complete.size} / #{list.tasks.size} completed", class: 'text-xs ml-1') %>
        </div>
        <div class="flex space-x-2">
          <span class="text-sm">
            <%= link_to "Edit", edit_list_path(list) %>
          </span>
          <span class="text-sm ml-2">
            <%= button_to "Delete", list, method: :delete, class: 'text-red-500 hover:text-red-600 text-sm underline hover:no-underline', form: { data: { turbo_confirm: "Are you sure?" } }%>
          </span>
        </div>
      </div>
    <% end %>
  </li>
</ul>

app/views/lists/_list_item.html.erb
<%= turbo_frame_tag dom_id(@list) do %>
  <div class="flex justify-between items-center">
    <%= link_to @list.name, list_path(@list), data: { turbo_frame: "_top"} %>
    <div>
      <span class="text-sm">
        <%= link_to "Edit", edit_list_path(@list) %>
      </span>
      <span class="text-sm ml-2">
        <%= link_to "Delete", @list, class: "text-red-500 hover:text-red-600 text-sm", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
      </span>
    </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<%= turbo_frame_tag dom_id(@list) do %>
  <%= form_with(model: @list, url: list_path(@list), method: :patch) do |form| %>
    <div class="flex items-center">
      <div class="flex-1">
        <%= form.text_field :name, class:'border px-2 w-full' %>
      </div>
      <%= form.button class: "btn-primary text-sm ml-2" do %>
        <span class="show-when-enabled">
          Update
        </span>
        <span class="show-when-disabled">Updating...</span>
      <% end %>
      <%= link_to "Cancel", lists_path, class: "ml-2 text-sm", data: { "turbo_frame": "_top" }  %>
    </div>
  <% end %>
<% end %>

app/views/lists/index.html.erb
<%= turbo_stream_from "lists" %>
<div class="max-w-lg mx-auto border min-h-screen p-4 bg-white">
  <div class="flex justify-between items-center mb-4 border-b pb-2">
    <p class="text-xl">Your to-dos</p>
    <p class="text-sm">Today is <%= Time.now.strftime("%b %d, %Y") %></p>
  </div>
  <% if @lists.present? %>
    <div id="lists">
      <%= render @lists %>
    </div>
    <%= link_to new_list_path, class: "btn-primary no-underline hover:text-white" do %>
      Create a new to-do
    <% end %>
  <% else %>
    <div class="mt-6">
      <%= link_to "Create a to-do", new_list_path, class: "btn-primary no-underline hover:text-white" %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="max-w-lg mx-auto border min-h-screen p-4 bg-white">
  <div class="flex border-b pb-2 mb-4">
    <p class="text-xl">Create a new to-do list</p>
  </div>
  <div>
    <%= render 'shared/errors', obj: @list %>
    <%= render 'form', list: @list %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="max-w-lg mx-auto border min-h-screen p-4 bg-white">
  <header class="flex justify-between items-center mb-4 border-b pb-2">
    <p class="text-xl"><%= @list.name %></p>
    <p class="text-sm">Created on <%= @list.created_at.strftime("%b %d, %Y") %></p>
  </header>
  <%= turbo_stream_from @list, :tasks %>
  <div id="incomplete-tasks">
    <%= render 'incomplete_tasks', list: @list, tasks: @list.tasks.where(status: "incomplete") %>
  </div>


  <div id="complete-tasks">
    <%= render 'complete_tasks', list: @list, tasks: @list.tasks.where(status: "complete") %>
  </div>

  <div class="flex items-center">
    <%= link_to 'Create tasks', new_list_task_path(@list), class: "btn-primary no-underline hover:text-white" %>
    <%= link_to 'Back to your to-dos', lists_path, class: "ml-3" %>
  </div>
</div>

app/views/lists/tasks/_form.html.erb
<%= form_with(model: @list, url: list_tasks_path, method: :post, data: { controller: 'nested-form',
                                                                         nested_form_wrapper_selector_value: '.nested-form-wrapper',
                                                                         turbo: false }) do |form| %>
  <template data-nested-form-target="template">
    <%= form.fields_for :tasks, Task.new, child_index: 'NEW_RECORD' do |task_fields| %>
      <%= render "task_form", f: task_fields %>
    <% end %>
  </template>

  <%= form.fields_for :tasks do |task_fields| %>
    <%= render 'task_form', f: task_fields %>
  <% end %>

  <div data-nested-form-target="target"></div>

  <button class="btn-secondary" type="button" data-action="nested-form#add">
    &plus; Add a task
  </button>

  <div class="flex items-center hidden mt-4" id="submit-task">
    <%= form.button class: "btn-primary" do %>
      <span class="show-when-enabled">
        Save to to-do list
      </span>
      <span class="show-when-disabled">Saving...</span>
    <% end %>
    <a href="/" class="text-sm ml-4">Nevermind, take me back</a>
  </div>
<% end %>

app/views/lists/tasks/_incomplete_task_item.html.erb
<%= turbo_frame_tag dom_id(@task) do  %>
  <div class="flex gap-4 items-start">
    <div class="flex-none" >
      <input type="checkbox"
              data-action="task#updateStatus"
              data-task-target="complete"
              data-task-list-value="<%= @list.id %>"
              data-task-task-value="<%= @task.id %>"
              <% if @task.complete? %> checked <% end %> >
    </div>
    <div class="flex-1"><%= @task.description %></div>
    <div class="flex">
      <span class="text-sm">
        <%= link_to "Edit", edit_list_task_path(@list, @task) %>
      </span>
      <span class="text-sm ml-2">
        <%= button_to "Delete",
              list_task_path(@list, @task),
              method: :delete,
              class: 'text-red-500 hover:text-red-600 text-sm underline hover:no-underline',
              form: { data: { turbo_confirm: "Are you sure?" }  }%>
      </span>
    </div>
  </div>
<% end %>

app/views/lists/tasks/_task_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>" data-controller="description">
  <div class="mb-4">
    <div class="flex justify-between items-center">
      <%= f.label :description %>
      <div>
        <button class="text-xs text-red-500" type="button" data-action="nested-form#remove">
          Remove
        </button>
      </div>
    </div>
    <%= f.text_field :description, class:'border p-2 w-full', required: true, data: { action: 'input->description#showSubmit' } %>
  </div>

  <%= f.hidden_field :_destroy %>
</div>

app/views/lists/tasks/edit.html.erb
  <%= turbo_frame_tag dom_id(@task) do %>
    <%= form_with(model: @task, url: list_task_path(@list, @task), method: :patch) do |form| %>
      <div class="flex gap-4 items-center">
        <div class="flex-none">
          <%= check_box_tag "", "", false, { disabled: true } %>
        </div>
          <div class="flex-1">
            <%= form.text_field :description, class:'border px-2 w-full' %>
          </div>
          <div>
            <%= form.button class: "btn-primary text-sm ml-2" do %>
              <span class="show-when-enabled">
                Update
              </span>
              <span class="show-when-disabled">Updating...</span>
            <% end %>
            <span class="text-sm ml-2">
              <%= link_to "Cancel", list_path(@list), class: "ml-2 text-sm", data: { "turbo_frame": "_top" }  %>
            </span>
          </div>
      </div>
    <% end %>
  <% end %>

app/views/lists/tasks/new.html.erb
<div class="max-w-lg mx-auto border min-h-screen p-4 bg-white">
  <div class="flex justify-between items-center mb-4 border-b pb-2">
    <div>
      <p class="text-xl">Create tasks</p>
      <p class="text-sm text-gray-400">to-do · <%= @list.name %></p>
    </div>
  </div>
  <div>
    <%= render 'shared/errors', obj: @task %>
    <%= render 'form', task: @task %>
  </div>
</div>

app/views/lists/tasks/status.turbo_stream.erb
<%= turbo_stream.update "incomplete-tasks" do %>
  <%= render 'lists/incomplete_tasks', list: @list, tasks: @list.tasks.where(status: "incomplete") %>
<% end %>

<%= turbo_stream.update "complete-tasks" do %>
  <%= render 'lists/complete_tasks', list: @list, tasks: @list.tasks.where(status: "complete") %>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="border-red border rounded p-2 mb-4">
    <p class="text-xs font-semibold mb-2 text-green-600">There was a problem</p>
    <ul>
      <% obj.errors.each do |msg| %>
        <a href="#<%= msg.attribute.to_s %>">
          <li class="text-sm"><%= msg.full_message %></li>
        </a>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice].present? %>
  <div class="mx-auto max-w-4xl" data-controller="flash">
    <article class="p-4 bg-blue-100 text-sm shadow-sm relative">
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div class="flex-1 ml-4">
          <%= notice %>
        </div>
      </div>
      <button class="rounded-full h-4 w-4 bg-white border-gray-300 absolute origin-top-right top-1 right-1 flex justify-center items-center border" data-action="click->flash#close">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </article>
  </div>
<% end %>

<% if flash[:success].present? %>
  <div class="mx-auto max-w-4xl" data-controller="flash">
    <article class="p-4 bg-green-100 text-sm shadow-sm relative">
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div class="flex-1 ml-4">
          <%= success %>
        </div>
      </div>
      <button class="rounded-full h-4 w-4 bg-white border-gray-300 absolute origin-top-right top-1 right-1 flex justify-center items-center border" data-action="click->flash#close">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </article>
  </div>
<% end %>

<% if flash[:warning].present? %>
  <div class="mx-auto max-w-4xl" data-controller="flash">
    <article class="p-4 bg-red-100 text-sm shadow-sm relative">
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div class="flex-1 ml-4">
          <%= warning %>
        </div>
      </div>
      <button class="rounded-full h-4 w-4 bg-white border-gray-300 absolute origin-top-right top-1 right-1 flex justify-center items-center border" data-action="click->flash#close">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </article>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="mx-auto max-w-4xl" data-controller="flash">
    <article class="p-4 bg-yellow-100 text-sm shadow-sm relative">
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div class="flex-1 ml-4">
          <%= alert %>
        </div>
      </div>
      <button class="rounded-full h-4 w-4 bg-white border-gray-300 absolute origin-top-right top-1 right-1 flex justify-center items-center border" data-action="click->flash#close">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </article>
  </div>
<% end %>

<%#= yield :flash %>